export const AuthCodes = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  OTP_SENT: 'OTP_SENT',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
} as const;

export const ErrorCodes = {
  USER_EXISTS: 'ERR_USER_EXISTS',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ERR_ACCOUNT_LOCKED',
  SOCIAL_AUTH_FAILED: 'ERR_SOCIAL_AUTH_FAILED',
  INVALID_OTP: 'ERR_INVALID_OTP',
  OTP_EXPIRED: 'ERR_OTP_EXPIRED',
  INVALID_RESET_TOKEN: 'ERR_INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'ERR_RESET_TOKEN_EXPIRED',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOO_MANY_REQUESTS: 'ERR_TOO_MANY_REQUESTS',
  INVALID_INPUT: 'ERR_INVALID_INPUT',
  INTERNAL: 'ERR_INTERNAL_SERVER',
} as const;
